//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rwp.RwpSvc {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SRBase", Namespace="http://schemas.datacontract.org/2004/07/RwpSvc")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Rwp.RwpSvc.SR))]
    public partial class SRBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReasonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ResultField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Reason {
            get {
                return this.ReasonField;
            }
            set {
                if ((object.ReferenceEquals(this.ReasonField, value) != true)) {
                    this.ReasonField = value;
                    this.RaisePropertyChanged("Reason");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Result {
            get {
                return this.ResultField;
            }
            set {
                if ((this.ResultField.Equals(value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SR", Namespace="http://schemas.datacontract.org/2004/07/RwpSvc")]
    [System.SerializableAttribute()]
    public partial class SR : Rwp.RwpSvc.SRBase {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="", ConfigurationName="RwpSvc.Practice")]
    public interface Practice {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Practice/GetData", ReplyAction="urn:Practice/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Practice/GetData", ReplyAction="urn:Practice/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Practice/GetCsvTeams", ReplyAction="urn:Practice/GetCsvTeamsResponse")]
        string GetCsvTeams();
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Practice/GetCsvTeams", ReplyAction="urn:Practice/GetCsvTeamsResponse")]
        System.Threading.Tasks.Task<string> GetCsvTeamsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Practice/GetCsvTeamsStream", ReplyAction="urn:Practice/GetCsvTeamsStreamResponse")]
        System.IO.Stream GetCsvTeamsStream();
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Practice/GetCsvTeamsStream", ReplyAction="urn:Practice/GetCsvTeamsStreamResponse")]
        System.Threading.Tasks.Task<System.IO.Stream> GetCsvTeamsStreamAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Practice/ImportCsvTeams", ReplyAction="urn:Practice/ImportCsvTeamsResponse")]
        Rwp.RwpSvc.SR ImportCsvTeams(System.IO.Stream stmCsv);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Practice/ImportCsvTeams", ReplyAction="urn:Practice/ImportCsvTeamsResponse")]
        System.Threading.Tasks.Task<Rwp.RwpSvc.SR> ImportCsvTeamsAsync(System.IO.Stream stmCsv);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Practice/ClearTeams", ReplyAction="urn:Practice/ClearTeamsResponse")]
        Rwp.RwpSvc.SR ClearTeams();
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Practice/ClearTeams", ReplyAction="urn:Practice/ClearTeamsResponse")]
        System.Threading.Tasks.Task<Rwp.RwpSvc.SR> ClearTeamsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Practice/ClearSlots", ReplyAction="urn:Practice/ClearSlotsResponse")]
        Rwp.RwpSvc.SR ClearSlots();
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Practice/ClearSlots", ReplyAction="urn:Practice/ClearSlotsResponse")]
        System.Threading.Tasks.Task<Rwp.RwpSvc.SR> ClearSlotsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Practice/ClearYear", ReplyAction="urn:Practice/ClearYearResponse")]
        Rwp.RwpSvc.SR ClearYear(int nYear);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Practice/ClearYear", ReplyAction="urn:Practice/ClearYearResponse")]
        System.Threading.Tasks.Task<Rwp.RwpSvc.SR> ClearYearAsync(int nYear);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Practice/GetCsvSlots", ReplyAction="urn:Practice/GetCsvSlotsResponse")]
        System.IO.Stream GetCsvSlots();
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Practice/GetCsvSlots", ReplyAction="urn:Practice/GetCsvSlotsResponse")]
        System.Threading.Tasks.Task<System.IO.Stream> GetCsvSlotsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Practice/ImportCsvSlots", ReplyAction="urn:Practice/ImportCsvSlotsResponse")]
        Rwp.RwpSvc.SR ImportCsvSlots(System.IO.Stream stmCsv);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Practice/ImportCsvSlots", ReplyAction="urn:Practice/ImportCsvSlotsResponse")]
        System.Threading.Tasks.Task<Rwp.RwpSvc.SR> ImportCsvSlotsAsync(System.IO.Stream stmCsv);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PracticeChannel : Rwp.RwpSvc.Practice, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PracticeClient : System.ServiceModel.ClientBase<Rwp.RwpSvc.Practice>, Rwp.RwpSvc.Practice {
        
        public PracticeClient() {
        }
        
        public PracticeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PracticeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PracticeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PracticeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public string GetCsvTeams() {
            return base.Channel.GetCsvTeams();
        }
        
        public System.Threading.Tasks.Task<string> GetCsvTeamsAsync() {
            return base.Channel.GetCsvTeamsAsync();
        }
        
        public System.IO.Stream GetCsvTeamsStream() {
            return base.Channel.GetCsvTeamsStream();
        }
        
        public System.Threading.Tasks.Task<System.IO.Stream> GetCsvTeamsStreamAsync() {
            return base.Channel.GetCsvTeamsStreamAsync();
        }
        
        public Rwp.RwpSvc.SR ImportCsvTeams(System.IO.Stream stmCsv) {
            return base.Channel.ImportCsvTeams(stmCsv);
        }
        
        public System.Threading.Tasks.Task<Rwp.RwpSvc.SR> ImportCsvTeamsAsync(System.IO.Stream stmCsv) {
            return base.Channel.ImportCsvTeamsAsync(stmCsv);
        }
        
        public Rwp.RwpSvc.SR ClearTeams() {
            return base.Channel.ClearTeams();
        }
        
        public System.Threading.Tasks.Task<Rwp.RwpSvc.SR> ClearTeamsAsync() {
            return base.Channel.ClearTeamsAsync();
        }
        
        public Rwp.RwpSvc.SR ClearSlots() {
            return base.Channel.ClearSlots();
        }
        
        public System.Threading.Tasks.Task<Rwp.RwpSvc.SR> ClearSlotsAsync() {
            return base.Channel.ClearSlotsAsync();
        }
        
        public Rwp.RwpSvc.SR ClearYear(int nYear) {
            return base.Channel.ClearYear(nYear);
        }
        
        public System.Threading.Tasks.Task<Rwp.RwpSvc.SR> ClearYearAsync(int nYear) {
            return base.Channel.ClearYearAsync(nYear);
        }
        
        public System.IO.Stream GetCsvSlots() {
            return base.Channel.GetCsvSlots();
        }
        
        public System.Threading.Tasks.Task<System.IO.Stream> GetCsvSlotsAsync() {
            return base.Channel.GetCsvSlotsAsync();
        }
        
        public Rwp.RwpSvc.SR ImportCsvSlots(System.IO.Stream stmCsv) {
            return base.Channel.ImportCsvSlots(stmCsv);
        }
        
        public System.Threading.Tasks.Task<Rwp.RwpSvc.SR> ImportCsvSlotsAsync(System.IO.Stream stmCsv) {
            return base.Channel.ImportCsvSlotsAsync(stmCsv);
        }
    }
}
