//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rwp.RwpSvcLocal {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RSRBase", Namespace="http://schemas.datacontract.org/2004/07/RwpSvc")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Rwp.RwpSvcLocal.TRSROfArrayOfCalItemQ1Zl4_P0R))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Rwp.RwpSvcLocal.RSR_CalItems))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Rwp.RwpSvcLocal.RSR))]
    public partial class RSRBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReasonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ResultField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Reason {
            get {
                return this.ReasonField;
            }
            set {
                if ((object.ReferenceEquals(this.ReasonField, value) != true)) {
                    this.ReasonField = value;
                    this.RaisePropertyChanged("Reason");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Result {
            get {
                return this.ResultField;
            }
            set {
                if ((this.ResultField.Equals(value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TRSROfArrayOfCalItemQ1Zl4_P0R", Namespace="http://schemas.datacontract.org/2004/07/RwpSvc")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Rwp.RwpSvcLocal.RSR_CalItems))]
    public partial class TRSROfArrayOfCalItemQ1Zl4_P0R : Rwp.RwpSvcLocal.RSRBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Rwp.RwpSvcLocal.CalItem[] TheValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Rwp.RwpSvcLocal.CalItem[] TheValue {
            get {
                return this.TheValueField;
            }
            set {
                if ((object.ReferenceEquals(this.TheValueField, value) != true)) {
                    this.TheValueField = value;
                    this.RaisePropertyChanged("TheValue");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RSR_CalItems", Namespace="http://schemas.datacontract.org/2004/07/RwpSvc")]
    [System.SerializableAttribute()]
    public partial class RSR_CalItems : Rwp.RwpSvcLocal.TRSROfArrayOfCalItemQ1Zl4_P0R {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RSR", Namespace="http://schemas.datacontract.org/2004/07/RwpSvc")]
    [System.SerializableAttribute()]
    public partial class RSR : Rwp.RwpSvcLocal.RSRBase {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CalItem", Namespace="http://schemas.datacontract.org/2004/07/RwpSvc")]
    [System.SerializableAttribute()]
    public partial class CalItem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime EndField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LocationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime StartField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime End {
            get {
                return this.EndField;
            }
            set {
                if ((this.EndField.Equals(value) != true)) {
                    this.EndField = value;
                    this.RaisePropertyChanged("End");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Location {
            get {
                return this.LocationField;
            }
            set {
                if ((object.ReferenceEquals(this.LocationField, value) != true)) {
                    this.LocationField = value;
                    this.RaisePropertyChanged("Location");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Start {
            get {
                return this.StartField;
            }
            set {
                if ((this.StartField.Equals(value) != true)) {
                    this.StartField = value;
                    this.RaisePropertyChanged("Start");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UID {
            get {
                return this.UIDField;
            }
            set {
                if ((object.ReferenceEquals(this.UIDField, value) != true)) {
                    this.UIDField = value;
                    this.RaisePropertyChanged("UID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServerInfo", Namespace="http://schemas.datacontract.org/2004/07/RwpSvc")]
    [System.SerializableAttribute()]
    public partial class ServerInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sServerNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sSqlServerHashField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sServerName {
            get {
                return this.sServerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.sServerNameField, value) != true)) {
                    this.sServerNameField = value;
                    this.RaisePropertyChanged("sServerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sSqlServerHash {
            get {
                return this.sSqlServerHashField;
            }
            set {
                if ((object.ReferenceEquals(this.sSqlServerHashField, value) != true)) {
                    this.sSqlServerHashField = value;
                    this.RaisePropertyChanged("sSqlServerHash");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="", ConfigurationName="RwpSvcLocal.Practice")]
    public interface Practice {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Practice/GetData", ReplyAction="urn:Practice/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Practice/GetData", ReplyAction="urn:Practice/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Practice/GetCsvTeams", ReplyAction="urn:Practice/GetCsvTeamsResponse")]
        string GetCsvTeams();
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Practice/GetCsvTeams", ReplyAction="urn:Practice/GetCsvTeamsResponse")]
        System.Threading.Tasks.Task<string> GetCsvTeamsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Practice/GetCsvTeamsStream", ReplyAction="urn:Practice/GetCsvTeamsStreamResponse")]
        System.IO.Stream GetCsvTeamsStream();
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Practice/GetCsvTeamsStream", ReplyAction="urn:Practice/GetCsvTeamsStreamResponse")]
        System.Threading.Tasks.Task<System.IO.Stream> GetCsvTeamsStreamAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Practice/ImportCsvTeams", ReplyAction="urn:Practice/ImportCsvTeamsResponse")]
        Rwp.RwpSvcLocal.RSR ImportCsvTeams(System.IO.Stream stmCsv);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Practice/ImportCsvTeams", ReplyAction="urn:Practice/ImportCsvTeamsResponse")]
        System.Threading.Tasks.Task<Rwp.RwpSvcLocal.RSR> ImportCsvTeamsAsync(System.IO.Stream stmCsv);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Practice/ClearTeams", ReplyAction="urn:Practice/ClearTeamsResponse")]
        Rwp.RwpSvcLocal.RSR ClearTeams();
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Practice/ClearTeams", ReplyAction="urn:Practice/ClearTeamsResponse")]
        System.Threading.Tasks.Task<Rwp.RwpSvcLocal.RSR> ClearTeamsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Practice/ClearSlots", ReplyAction="urn:Practice/ClearSlotsResponse")]
        Rwp.RwpSvcLocal.RSR ClearSlots();
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Practice/ClearSlots", ReplyAction="urn:Practice/ClearSlotsResponse")]
        System.Threading.Tasks.Task<Rwp.RwpSvcLocal.RSR> ClearSlotsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Practice/ClearYear", ReplyAction="urn:Practice/ClearYearResponse")]
        Rwp.RwpSvcLocal.RSR ClearYear(int nYear);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Practice/ClearYear", ReplyAction="urn:Practice/ClearYearResponse")]
        System.Threading.Tasks.Task<Rwp.RwpSvcLocal.RSR> ClearYearAsync(int nYear);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Practice/GetCsvSlots", ReplyAction="urn:Practice/GetCsvSlotsResponse")]
        System.IO.Stream GetCsvSlots();
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Practice/GetCsvSlots", ReplyAction="urn:Practice/GetCsvSlotsResponse")]
        System.Threading.Tasks.Task<System.IO.Stream> GetCsvSlotsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Practice/GetCalendarForTeam", ReplyAction="urn:Practice/GetCalendarForTeamResponse")]
        Rwp.RwpSvcLocal.RSR_CalItems GetCalendarForTeam(string sTeamName);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Practice/GetCalendarForTeam", ReplyAction="urn:Practice/GetCalendarForTeamResponse")]
        System.Threading.Tasks.Task<Rwp.RwpSvcLocal.RSR_CalItems> GetCalendarForTeamAsync(string sTeamName);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Practice/ImportCsvSlots", ReplyAction="urn:Practice/ImportCsvSlotsResponse")]
        Rwp.RwpSvcLocal.RSR ImportCsvSlots(System.IO.Stream stmCsv);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Practice/ImportCsvSlots", ReplyAction="urn:Practice/ImportCsvSlotsResponse")]
        System.Threading.Tasks.Task<Rwp.RwpSvcLocal.RSR> ImportCsvSlotsAsync(System.IO.Stream stmCsv);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Practice/GetServerInfo", ReplyAction="urn:Practice/GetServerInfoResponse")]
        Rwp.RwpSvcLocal.ServerInfo GetServerInfo();
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Practice/GetServerInfo", ReplyAction="urn:Practice/GetServerInfoResponse")]
        System.Threading.Tasks.Task<Rwp.RwpSvcLocal.ServerInfo> GetServerInfoAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PracticeChannel : Rwp.RwpSvcLocal.Practice, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PracticeClient : System.ServiceModel.ClientBase<Rwp.RwpSvcLocal.Practice>, Rwp.RwpSvcLocal.Practice {
        
        public PracticeClient() {
        }
        
        public PracticeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PracticeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PracticeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PracticeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public string GetCsvTeams() {
            return base.Channel.GetCsvTeams();
        }
        
        public System.Threading.Tasks.Task<string> GetCsvTeamsAsync() {
            return base.Channel.GetCsvTeamsAsync();
        }
        
        public System.IO.Stream GetCsvTeamsStream() {
            return base.Channel.GetCsvTeamsStream();
        }
        
        public System.Threading.Tasks.Task<System.IO.Stream> GetCsvTeamsStreamAsync() {
            return base.Channel.GetCsvTeamsStreamAsync();
        }
        
        public Rwp.RwpSvcLocal.RSR ImportCsvTeams(System.IO.Stream stmCsv) {
            return base.Channel.ImportCsvTeams(stmCsv);
        }
        
        public System.Threading.Tasks.Task<Rwp.RwpSvcLocal.RSR> ImportCsvTeamsAsync(System.IO.Stream stmCsv) {
            return base.Channel.ImportCsvTeamsAsync(stmCsv);
        }
        
        public Rwp.RwpSvcLocal.RSR ClearTeams() {
            return base.Channel.ClearTeams();
        }
        
        public System.Threading.Tasks.Task<Rwp.RwpSvcLocal.RSR> ClearTeamsAsync() {
            return base.Channel.ClearTeamsAsync();
        }
        
        public Rwp.RwpSvcLocal.RSR ClearSlots() {
            return base.Channel.ClearSlots();
        }
        
        public System.Threading.Tasks.Task<Rwp.RwpSvcLocal.RSR> ClearSlotsAsync() {
            return base.Channel.ClearSlotsAsync();
        }
        
        public Rwp.RwpSvcLocal.RSR ClearYear(int nYear) {
            return base.Channel.ClearYear(nYear);
        }
        
        public System.Threading.Tasks.Task<Rwp.RwpSvcLocal.RSR> ClearYearAsync(int nYear) {
            return base.Channel.ClearYearAsync(nYear);
        }
        
        public System.IO.Stream GetCsvSlots() {
            return base.Channel.GetCsvSlots();
        }
        
        public System.Threading.Tasks.Task<System.IO.Stream> GetCsvSlotsAsync() {
            return base.Channel.GetCsvSlotsAsync();
        }
        
        public Rwp.RwpSvcLocal.RSR_CalItems GetCalendarForTeam(string sTeamName) {
            return base.Channel.GetCalendarForTeam(sTeamName);
        }
        
        public System.Threading.Tasks.Task<Rwp.RwpSvcLocal.RSR_CalItems> GetCalendarForTeamAsync(string sTeamName) {
            return base.Channel.GetCalendarForTeamAsync(sTeamName);
        }
        
        public Rwp.RwpSvcLocal.RSR ImportCsvSlots(System.IO.Stream stmCsv) {
            return base.Channel.ImportCsvSlots(stmCsv);
        }
        
        public System.Threading.Tasks.Task<Rwp.RwpSvcLocal.RSR> ImportCsvSlotsAsync(System.IO.Stream stmCsv) {
            return base.Channel.ImportCsvSlotsAsync(stmCsv);
        }
        
        public Rwp.RwpSvcLocal.ServerInfo GetServerInfo() {
            return base.Channel.GetServerInfo();
        }
        
        public System.Threading.Tasks.Task<Rwp.RwpSvcLocal.ServerInfo> GetServerInfoAsync() {
            return base.Channel.GetServerInfoAsync();
        }
    }
}
